CREATE DATABASE [@Database]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'@Database', FILENAME = N'D:\SGBD\MS-SQL-Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\@Database.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'@Database_log', FILENAME = N'D:\SGBD\MS-SQL-Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\@Database_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 COLLATE Latin1_General_CI_AS
GO
ALTER DATABASE [@Database] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [@Database] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [@Database] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [@Database] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [@Database] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [@Database] SET ARITHABORT OFF 
GO
ALTER DATABASE [@Database] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [@Database] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [@Database] SET AUTO_CREATE_STATISTICS OFF
GO
ALTER DATABASE [@Database] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [@Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [@Database] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [@Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [@Database] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [@Database] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [@Database] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [@Database] SET  DISABLE_BROKER 
GO
ALTER DATABASE [@Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [@Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [@Database] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [@Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [@Database] SET  READ_WRITE 
GO
ALTER DATABASE [@Database] SET RECOVERY FULL 
GO
ALTER DATABASE [@Database] SET  MULTI_USER 
GO
ALTER DATABASE [@Database] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [@Database] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [@Database] SET DELAYED_DURABILITY = DISABLED 
GO
USE [@Database]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [@Database] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
